// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIlcGZK-izbnmZD8g_vXz5slx_H1T7qUQ',
    appId: '1:799155321879:web:6cf316e2f16eb649d17052',
    messagingSenderId: '799155321879',
    projectId: 'smiles-alpha',
    authDomain: 'smiles-alpha.firebaseapp.com',
    storageBucket: 'smiles-alpha.firebasestorage.app',
    measurementId: 'G-75ME5YDS25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCamwxRWSTFMxQVdikU3y_1aq57pMJT64g',
    appId: '1:799155321879:android:6579d89177660b08d17052',
    messagingSenderId: '799155321879',
    projectId: 'smiles-alpha',
    storageBucket: 'smiles-alpha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-6AQ3OJ8WiVL0mzlNL6_qgjOK0UCq4o',
    appId: '1:799155321879:ios:fdce97b1dbd513ccd17052',
    messagingSenderId: '799155321879',
    projectId: 'smiles-alpha',
    storageBucket: 'smiles-alpha.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-6AQ3OJ8WiVL0mzlNL6_qgjOK0UCq4o',
    appId: '1:799155321879:ios:fdce97b1dbd513ccd17052',
    messagingSenderId: '799155321879',
    projectId: 'smiles-alpha',
    storageBucket: 'smiles-alpha.firebasestorage.app',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIlcGZK-izbnmZD8g_vXz5slx_H1T7qUQ',
    appId: '1:799155321879:web:49ff2019ad477ab9d17052',
    messagingSenderId: '799155321879',
    projectId: 'smiles-alpha',
    authDomain: 'smiles-alpha.firebaseapp.com',
    storageBucket: 'smiles-alpha.firebasestorage.app',
    measurementId: 'G-T8P3PHYE8R',
  );
}
